export type Category = "Físico" | "Digital" | "Personalizado";
export type Badge = "Nuevo" | "Oferta" | "Más vendido" | "Agotado";

export interface Producto {
  id: number;
  slug: string;
  name: string;
  category: Category;
  price: string;
  priceNum: number;
  priceOld?: string;
  badge?: Badge;
  desc: string;
  descLong: string;
  gradient: string;
  features: string[];
  details: { label: string; value: string }[];
  imageUrl?: string;
}

export const productos: Producto[] = [
  {
    id: 1,
    slug: "kit-de-inicio-ritual",
    name: "Kit de Inicio Ritual",
    category: "Físico",
    price: "$45",
    priceNum: 45,
    badge: "Más vendido",
    desc: "Cristales, hierbas secas y vela ritual seleccionados con intención para tu primer altar.",
    descLong: "El Kit de Inicio Ritual es la puerta de entrada perfecta para quienes quieren comenzar una práctica espiritual concreta y con sentido. Cada elemento fue seleccionado con intención: no son objetos decorativos, son herramientas reales de trabajo energético. Viene con una guía de uso para que sepas exactamente cómo integrar cada pieza en tu vida cotidiana.",
    gradient: "from-verde via-celeste to-morado-light",
    features: [
      "Cristal de cuarzo transparente",
      "Vela ritual artesanal",
      "Mezcla de hierbas sagradas",
      "Incienso de palo santo",
      "Guía de uso en PDF",
      "Bolsa de tela orgánica",
    ],
    details: [
      { label: "Categoría",  value: "Físico" },
      { label: "Envío",      value: "Todo el país" },
      { label: "Tiempo",     value: "5 a 10 días hábiles" },
      { label: "Peso",       value: "~400g" },
    ],
  },
  {
    id: 2,
    slug: "vela-ritualica",
    name: "Vela Rituálica",
    category: "Personalizado",
    price: "$35",
    priceNum: 35,
    desc: "Elaborada a tu pedido con tus intenciones, hierbas específicas y color a elección.",
    descLong: "Cada vela rituálica es única. Se elabora a mano con tu intención específica: amor, abundancia, protección, claridad o cualquier propósito que traigas. Lleva hierbas asociadas a esa intención, aceites esenciales y un color cargado simbólicamente. Con ella recibirás instrucciones para el ritual de encendido.",
    gradient: "from-dorado via-rosa to-morado",
    features: [
      "Elaborada a mano con tu intención",
      "Hierbas rituales según propósito",
      "Aceites esenciales naturales",
      "Color elegido simbólicamente",
      "Instrucciones de ritual incluidas",
    ],
    details: [
      { label: "Categoría",  value: "Personalizado" },
      { label: "Tiempo",     value: "7 días de elaboración" },
      { label: "Envío",      value: "Todo el país" },
      { label: "Duración",   value: "~30 horas de quemado" },
    ],
  },
  {
    id: 3,
    slug: "cristal-cuarzo-rosa",
    name: "Cristal de Cuarzo Rosa",
    category: "Físico",
    price: "$22",
    priceNum: 22,
    badge: "Nuevo",
    desc: "Cuarzo rosa natural de alta calidad, ideal para rituales de amor propio y apertura del corazón.",
    descLong: "El cuarzo rosa es la piedra del amor por excelencia — pero no solo del amor romántico. Es una herramienta de sanación del corazón, de apertura a la ternura y de fortalecimiento del amor propio. Cada pieza es natural, única y viene energizada con intención antes de enviarse.",
    gradient: "from-rosa via-morado-light to-celeste",
    features: [
      "Cuarzo rosa natural (no sintético)",
      "Tamaño mediano: 5 a 7 cm",
      "Energizado antes del envío",
      "Guía de uso y cuidado",
      "Bolsita de tela incluida",
    ],
    details: [
      { label: "Categoría",  value: "Físico" },
      { label: "Material",   value: "Cuarzo rosa natural" },
      { label: "Tamaño",     value: "5-7 cm aprox." },
      { label: "Envío",      value: "Todo el país" },
    ],
  },
  {
    id: 4,
    slug: "set-hierbas-rituales",
    name: "Set de Hierbas Rituales",
    category: "Físico",
    price: "$18",
    priceNum: 18,
    priceOld: "$24",
    badge: "Oferta",
    desc: "Mezcla de lavanda, romero, manzanilla y salvia blanca. Perfectas para sahumerios y limpiezas.",
    descLong: "Las hierbas sagradas son aliadas espirituales desde tiempos ancestrales. Este set incluye una selección de cuatro hierbas con propiedades energéticas complementarias: lavanda para la paz, romero para la protección, manzanilla para la claridad y salvia blanca para la limpieza profunda. Ideales para sahumerios, baños rituales e infusiones con intención.",
    gradient: "from-verde via-verde-light to-dorado",
    features: [
      "Lavanda — paz y calma",
      "Romero — protección y claridad",
      "Manzanilla — suavidad y apertura",
      "Salvia blanca — limpieza energética",
      "Guía de usos incluida",
    ],
    details: [
      { label: "Categoría",  value: "Físico" },
      { label: "Contenido",  value: "4 hierbas, ~20g c/u" },
      { label: "Origen",     value: "Plantas orgánicas" },
      { label: "Envío",      value: "Todo el país" },
    ],
  },
  {
    id: 5,
    slug: "incienso-sagrado",
    name: "Incienso Sagrado",
    category: "Físico",
    price: "$14",
    priceNum: 14,
    desc: "Conos y varillas artesanales con fragancias de palo santo, mirra y nag champa.",
    descLong: "El incienso es una de las herramientas rituales más antiguas del mundo. Este pack artesanal incluye varillas y conos en tres fragancias de alta vibración: palo santo para limpiar y elevar el espacio, mirra para profundizar la conexión espiritual y nag champa para la meditación y la presencia. Sin químicos artificiales.",
    gradient: "from-tierra-light via-dorado to-rosa",
    features: [
      "10 varillas de palo santo",
      "10 varillas de nag champa",
      "6 conos de mirra",
      "Sin químicos ni aditivos artificiales",
      "Quemador de madera incluido",
    ],
    details: [
      { label: "Categoría",  value: "Físico" },
      { label: "Contenido",  value: "26 piezas totales" },
      { label: "Duración",   value: "~30 min por varilla" },
      { label: "Envío",      value: "Todo el país" },
    ],
  },
  {
    id: 6,
    slug: "piedras-de-proteccion",
    name: "Piedras de Protección",
    category: "Físico",
    price: "$30",
    priceNum: 30,
    desc: "Set de obsidiana negra, ojo de tigre y turmalina negra. Escudo energético para tu espacio.",
    descLong: "Algunas piedras tienen una energía densa y protectora que actúa como escudo frente a energías negativas, pensamientos intrusivos y ambientes cargados. Este set de tres reúne las más poderosas del mundo mineral para la protección: obsidiana negra para absorber negatividad, ojo de tigre para la claridad mental bajo presión, y turmalina negra para el campo electromagnético.",
    gradient: "from-morado-dark via-morado to-morado-light",
    features: [
      "Obsidiana negra — absorbe negatividad",
      "Ojo de tigre — claridad y fuerza",
      "Turmalina negra — protección electromagnética",
      "Guía de uso y cuidado",
      "Bolsita de cuero natural",
    ],
    details: [
      { label: "Categoría",  value: "Físico" },
      { label: "Piedras",    value: "3 piezas naturales" },
      { label: "Tamaño",     value: "3-5 cm aprox." },
      { label: "Envío",      value: "Todo el país" },
    ],
  },
  {
    id: 7,
    slug: "oraculo-de-la-reina",
    name: "Oráculo de la Reina",
    category: "Digital",
    price: "$25",
    priceNum: 25,
    desc: "Deck de 40 cartas digitales con guía de interpretación para tu práctica diaria.",
    descLong: "El Oráculo de la Reina es un mazo de 40 cartas diseñado para la práctica diaria de autoconocimiento. Cada carta lleva un mensaje directo, una pregunta de reflexión y una imagen simbólica. El archivo viene en formato PDF de alta resolución listo para imprimir o usar desde tu pantalla. Incluye guía completa de interpretación y sugerencias de tiradas.",
    gradient: "from-morado via-morado-light to-rosa",
    features: [
      "40 cartas de oráculo en PDF",
      "Alta resolución para imprimir",
      "Guía completa de interpretación",
      "3 tiradas sugeridas",
      "Descarga inmediata tras el pago",
    ],
    details: [
      { label: "Categoría",  value: "Digital" },
      { label: "Formato",    value: "PDF descargable" },
      { label: "Resolución", value: "300 DPI" },
      { label: "Acceso",     value: "Inmediato" },
    ],
  },
  {
    id: 8,
    slug: "almanaque-lunar-2025",
    name: "Almanaque Lunar 2025",
    category: "Digital",
    price: "$12",
    priceNum: 12,
    desc: "PDF descargable con ciclos lunares, rituales sugeridos y afirmaciones para cada fase.",
    descLong: "El Almanaque Lunar 2025 es tu guía mes a mes para vivir en sintonía con los ciclos de la luna. Cada página incluye las fechas de las fases lunares, el signo zodiacal en el que transita, rituales sugeridos para cada momento y afirmaciones para trabajar la energía del mes. Ideal para imprimir y tener en tu altar o mesa de trabajo.",
    gradient: "from-morado-mid via-morado to-rosa",
    features: [
      "12 meses de ciclos lunares",
      "Rituales para cada fase",
      "Afirmaciones mensuales",
      "Fechas de eclipses y eventos",
      "Diseño para imprimir o usar digital",
    ],
    details: [
      { label: "Categoría",  value: "Digital" },
      { label: "Formato",    value: "PDF descargable" },
      { label: "Páginas",    value: "48 páginas" },
      { label: "Acceso",     value: "Inmediato" },
    ],
  },
  {
    id: 9,
    slug: "carta-astral-pdf",
    name: "Carta Astral PDF",
    category: "Digital",
    price: "$30",
    priceNum: 30,
    badge: "Nuevo",
    desc: "Interpretación completa de tu carta natal en PDF: planetas, casas, aspectos y tránsitos actuales.",
    descLong: "Tu carta natal es el mapa de tu psicología, tus talentos y tus desafíos. Este PDF personalizado incluye el análisis completo de tu carta: los planetas en sus signos y casas, los aspectos más importantes, los tránsitos actuales y una síntesis de los temas centrales de tu vida. Para pedirlo necesitás fecha, hora y lugar de nacimiento.",
    gradient: "from-celeste via-morado to-rosa",
    features: [
      "Análisis completo de carta natal",
      "Planetas, signos y casas",
      "Aspectos más relevantes",
      "Tránsitos del año en curso",
      "12 páginas en PDF personalizado",
    ],
    details: [
      { label: "Categoría",  value: "Digital" },
      { label: "Entrega",    value: "3 a 5 días hábiles" },
      { label: "Requiere",   value: "Fecha, hora y lugar de nac." },
      { label: "Formato",    value: "PDF personalizado" },
    ],
  },
  {
    id: 10,
    slug: "agenda-espiritual-2025",
    name: "Agenda Espiritual 2025",
    category: "Digital",
    price: "$15",
    priceNum: 15,
    priceOld: "$20",
    badge: "Oferta",
    desc: "Planificador digital con lunas, fechas de poder, rituales estacionales y espacio de reflexión.",
    descLong: "La Agenda Espiritual 2025 combina lo práctico con lo sagrado. Cada semana tiene espacio para tus intenciones, tus gratitudes y tu reflexión. Incluye las lunas del año, las fechas de solsticios y equinoccios, rituales estacionales y páginas especiales para cada inicio de mes. Compatible con GoodNotes, Notability y cualquier app de anotaciones.",
    gradient: "from-morado via-rosa to-dorado",
    features: [
      "Planificador semanal y mensual",
      "Todas las lunas del año",
      "Rituales de cada estación",
      "Solsticios y equinoccios",
      "Compatible con apps de notas digitales",
    ],
    details: [
      { label: "Categoría",  value: "Digital" },
      { label: "Formato",    value: "PDF interactivo" },
      { label: "Páginas",    value: "200+ páginas" },
      { label: "Acceso",     value: "Inmediato" },
    ],
  },
  {
    id: 11,
    slug: "ritual-personalizado",
    name: "Ritual Personalizado",
    category: "Personalizado",
    price: "$60",
    priceNum: 60,
    desc: "Diseño de un ritual completo a medida: propósito, elementos, guía paso a paso y seguimiento.",
    descLong: "Un ritual diseñado específicamente para vos, para tu momento de vida y tu intención particular. Empezamos con un cuestionario donde me contás lo que estás atravesando, lo que querés atraer o soltar. A partir de ahí diseño un ritual paso a paso con los elementos que podés conseguir, los tiempos, las palabras y las acciones. Con seguimiento de 7 días.",
    gradient: "from-dorado via-morado to-rosa",
    features: [
      "Cuestionario de intención previo",
      "Ritual diseñado a medida",
      "Lista de elementos necesarios",
      "Guía escrita paso a paso",
      "Seguimiento por 7 días",
    ],
    details: [
      { label: "Categoría",  value: "Personalizado" },
      { label: "Entrega",    value: "5 a 7 días hábiles" },
      { label: "Formato",    value: "PDF + soporte por mensaje" },
      { label: "Seguimiento", value: "7 días incluidos" },
    ],
  },
  {
    id: 12,
    slug: "kit-luna-nueva",
    name: "Kit Luna Nueva",
    category: "Físico",
    price: "$38",
    priceNum: 38,
    desc: "Todo lo necesario para tu ritual de luna nueva: vela, cristal, papel de intención y guía.",
    descLong: "La luna nueva es el momento perfecto para plantar intenciones, abrir ciclos y conectar con lo que querés crear. Este kit tiene todo lo necesario para hacer ese ritual de manera simple pero poderosa: vela blanca artesanal, cristal de cuarzo transparente, papel especial para escribir intenciones, pétalos de jazmín y la guía completa del ritual paso a paso.",
    gradient: "from-morado-dark via-celeste to-morado-light",
    features: [
      "Vela blanca artesanal",
      "Cristal de cuarzo transparente",
      "Papel de intenciones (x3)",
      "Pétalos de jazmín secos",
      "Guía del ritual de luna nueva",
    ],
    details: [
      { label: "Categoría",  value: "Físico" },
      { label: "Envío",      value: "Todo el país" },
      { label: "Tiempo",     value: "5 a 10 días hábiles" },
      { label: "Peso",       value: "~300g" },
    ],
  },
];
